sudo: required

language: node_js

services:
  - docker

after_script:
  - docker build -t node-k8s-seed .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push danielpacak/node-k8s-seed;
