sudo: required

language: node_js

services:
  - docker

after_success:
  - docker build -t $DOCKER_USERNAME/node-k8s-seed .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/node-k8s-seed;
