---
apiVersion: v1
kind: Namespace
metadata:
  name: node-k8s-seed
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-k8s-seed
  namespace: node-k8s-seed
spec:
  template:
    metadata:
      labels:
        app: node-k8s-seed
    spec:
      containers:
      - name: node-k8s-seed
        image: node-k8s-seed:0.0.1-alpha-2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: node-k8s-seed
  namespace: node-k8s-seed
spec:
  selector:
    app: node-k8s-seed
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
